apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-app
spec:
  template:
    spec:
      containers:
      - name: nginx
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"