apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-demo-app
  name: argocd-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-demo-app
  template:
    metadata:
      labels:
        app: argocd-demo-app
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello
        ports:
          - containerPort: 80