apiVersion: v1
kind: Service
metadata:
  name: argocd-demo-app-service
  labels:
    app: argocd-demo-app  
spec:
  selector:
    matchLabels:
      app: argocd-demo-app
  ports:
  - port: 80
    targetPort: 80
